"""Excel model scaffolds (Phase 5).

LEAN, rebuildable skeletons — drivers + LIVE Excel formulas, seeded from the
Phase-3/4 engines — NOT finished black-box models, and NOT to be presented in an
interview as autogenerated (see CLAUDE.md + models/MODEL_NOTES.md).
"""

from .builder import (
    ModelBuildResult,
    ModelInputs,
    build_models,
    build_workbook,
)

__all__ = ["build_models", "build_workbook", "ModelBuildResult", "ModelInputs"]
