"""Excel model-scaffold generator.

Produces ``models/<TICKER>_model.xlsx`` — a LEAN, rebuildable skeleton (NOT a
finished black-box model, NOT to be presented in an interview as autogenerated;
CLAUDE.md non-goal). Drivers are input cells; valuation is LIVE Excel formulas
off those drivers, so the analyst flexes assumptions IN Excel. Values are SEEDED
from the Phase-3/4 engines (``comps.run_comps`` / ``spinoffs.run_track``) — the
math is never re-implemented in Python and dumped as static numbers; the Excel
formulas mirror the engine so the reverse-DCF ties to the ``comps <TICKER>`` CLI.

Downside-first: bear is the first data column on every valuation tab and carries
the loudest styling. Source-tagged: every input is marked input / formula /
EDGAR-primary / yfinance-non-primary / analyst-assumption on the Inputs tab.

Split for testability: ``build_models`` does the (networked) data gather, then
``build_workbook`` assembles the file from a plain ``ModelInputs`` bundle — the
offline tests build a synthetic bundle and never touch the network.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

from openpyxl import Workbook
from openpyxl.formatting.rule import DataBarRule, FormulaRule
from openpyxl.styles import Font, PatternFill
from openpyxl.workbook.defined_name import DefinedName

from ..adapters import EdgarProvider
from ..comps import run_comps
from ..comps.comps import CompsResult, TickerAnalysis, _last_shares
from ..comps.normalized import DEFAULT_TAX_RATE
from ..config import models_dir
from ..metrics import net_debt_fy, tangible_book_value_fy
from ..spinoffs.discovery import SpinoffRecord
from ..spinoffs.tracker import run_track
from . import styles as st

# Sheet titles (kept stable — tests assert on them).
SHEET_INPUTS = "Inputs & Sources"
SHEET_DCF = "DCF & Reverse-DCF"
SHEET_BANK = "Bank Valuation"
SHEET_NORM = "Normalized Earnings"
SHEET_FOOTBALL = "Football Field"
SHEET_SOTP = "Spin-off SOTP"
SHEET_NOTES = "Notes"

CASE_COLS = ("B", "C", "D")  # bear, base, bull — bear FIRST (downside-first)


# --------------------------------------------------------------------------- #
# Result + input bundles
# --------------------------------------------------------------------------- #

@dataclass
class ModelInputs:
    """Everything ``build_workbook`` needs — decoupled from the network so the
    offline tests can hand-build a synthetic bundle."""
    comps: CompsResult
    shares: float
    net_debt: float
    tbv_per_share: float
    is_bank: bool
    spinoff: SpinoffRecord | None = None


@dataclass
class ModelBuildResult:
    ticker: str
    xlsx_path: Path
    is_bank: bool
    has_sotp: bool
    comps_result: CompsResult
    tracker_result: object | None = None


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #

def _ok(x) -> bool:
    """True if x is a usable finite number."""
    if x is None:
        return False
    try:
        return not (isinstance(x, float) and (math.isnan(x) or math.isinf(x)))
    except (TypeError, ValueError):
        return False


def _case(subj: TickerAnalysis, label: str):
    for c in subj.dcf_cases:
        if c.label == label:
            return c
    return None


def _peer_pe_stats(peer_table, subject_ticker: str) -> tuple[float, float, float]:
    """min / median / max P/E across the *individual* peers (excludes the subject
    and the PEER_MEDIAN / PEER_MEAN summary rows). Real peer range for the
    football field."""
    if peer_table is None or peer_table.empty or "pe" not in peer_table.columns:
        return (float("nan"),) * 3
    drop = {subject_ticker, "PEER_MEDIAN", "PEER_MEAN"}
    peers = peer_table[~peer_table.index.isin(drop)]
    pe = peers["pe"].dropna()
    if pe.empty:
        return (float("nan"),) * 3
    return float(pe.min()), float(pe.median()), float(pe.max())


def _seeds(mi: ModelInputs) -> dict:
    """Flatten the engine outputs into the scalar seeds the cells read from."""
    subj = mi.comps.subject
    norm = subj.normalized
    base, bear, bull = _case(subj, "base"), _case(subj, "bear"), _case(subj, "bull")
    bands = subj.history.bands if subj.history else {}
    pe = bands.get("PE")
    ptbv = bands.get("P_TBV")
    p_min, p_med, p_max = _peer_pe_stats(mi.comps.peer_table, subj.ticker)
    return {
        "wacc": mi.comps.wacc,
        "tg": mi.comps.terminal_growth,
        "years": int(mi.comps.forecast_years),
        "tax": norm.tax_rate if norm else DEFAULT_TAX_RATE,
        "price": subj.price,
        "mcap": subj.market_cap,
        "shares": mi.shares,
        "net_debt": mi.net_debt,
        "fcff0_base": base.fcf0 if base else float("nan"),
        "fcff0_bear": bear.fcf0 if bear else float("nan"),
        "fcff0_bull": bull.fcf0 if bull else float("nan"),
        "assumed_g": base.assumed_growth if base else float("nan"),
        "implied_g_base": base.implied_growth if base else float("nan"),
        "implied_g_bear": bear.implied_growth if bear else float("nan"),
        "implied_g_bull": bull.implied_growth if bull else float("nan"),
        "revenue": norm.current_revenue if norm else float("nan"),
        "mean_opm": norm.mean_op_margin if norm else float("nan"),
        "trough_opm": norm.trough_op_margin if norm else float("nan"),
        "int_exp": norm.interest_expense if norm else float("nan"),
        "trailing_pe": norm.trailing_pe if norm else float("nan"),
        "tbv_ps": mi.tbv_per_share,
        "pe_p25": pe.p25 if pe else float("nan"),
        "pe_median": pe.median if pe else float("nan"),
        "pe_p75": pe.p75 if pe else float("nan"),
        "ptbv_p25": ptbv.p25 if ptbv else float("nan"),
        "ptbv_median": ptbv.median if ptbv else float("nan"),
        "ptbv_p75": ptbv.p75 if ptbv else float("nan"),
        "peer_pe_min": p_min,
        "peer_pe_median": p_med,
        "peer_pe_max": p_max,
    }


# --------------------------------------------------------------------------- #
# Tab: Inputs & Sources (the shared driver/assumption + source tab)
# --------------------------------------------------------------------------- #

def _inputs_tab(ws, mi, s, names, bank, has_dcf, has_norm) -> None:
    subj = mi.comps.subject
    st.title(ws, f"Inputs & Sources — {subj.ticker}  ({'bank' if bank else 'non-bank'})")
    ws.cell(row=2, column=1,
            value="Every cell below is tagged. Formulas on the other tabs read these via "
                  "named ranges (e.g. =WACC). Edit amber inputs to flex; green/seed cells recompute.")
    st.header_row(ws, 4, ["Driver", "Value", "Type", "Source", "Note"])
    row = 5

    def drv(label, value, kind, source, note, fmt=None, name=None):
        nonlocal row
        ws.cell(row=row, column=1, value=label)
        st.write_cell(ws, row, 2, value, kind, fmt)
        ws.cell(row=row, column=3, value=kind)
        ws.cell(row=row, column=4, value=source)
        ws.cell(row=row, column=5, value=note)
        if name:
            names[name] = (SHEET_INPUTS, f"B{row}")
        row += 1

    def section(text):
        nonlocal row
        c = ws.cell(row=row, column=1, value=text)
        c.font = Font(bold=True, italic=True)
        row += 1

    section("Valuation drivers (assumptions)")
    drv("WACC", s["wacc"], st.ASSUMPTION, "config valuation.wacc / CLI --wacc",
        "discount rate", st.FMT_PCT, "WACC")
    drv("Terminal growth", s["tg"], st.ASSUMPTION, "config valuation.terminal_growth",
        "Gordon perpetuity g", st.FMT_PCT, "TERM_G")
    drv("Forecast years", s["years"], st.ASSUMPTION, "config valuation.forecast_years",
        "explicit horizon", st.FMT_INT, "YEARS")
    drv("Tax rate", s["tax"], st.ASSUMPTION, "normalized.py DEFAULT_TAX_RATE",
        "for normalized NOPAT", st.FMT_PCT, "TAX")
    drv("WACC stress (bear)", 0.01, st.ASSUMPTION, "reverse_dcf.build_cases default",
        "bear WACC add-on", st.FMT_PCT, "WACC_STRESS")
    drv("Terminal-g stress (bear)", 0.005, st.ASSUMPTION, "reverse_dcf.build_cases default",
        "bear terminal-g haircut", st.FMT_PCT, "TG_STRESS")

    section("Market (yfinance — non-primary)")
    drv("Current price", s["price"], st.YFINANCE, "yfinance (non-primary)",
        "quote; MoS measured vs this", st.FMT_PRICE, "PRICE")
    drv("Market cap", s["mcap"], st.YFINANCE, "yfinance (non-primary)",
        "price x shares fallback", st.FMT_USD_M, "MKT_CAP")

    section("Capital structure & shares (SEC EDGAR — primary)")
    drv("Diluted shares", s["shares"], st.EDGAR, "EDGAR WeightedAverageSharesDiluted",
        "same denominator as the DCF", st.FMT_INT, "SHARES")
    drv("Net debt", s["net_debt"], st.EDGAR, "EDGAR total debt − cash (NaN→0)",
        "subtracted to get equity", st.FMT_USD_M, "NET_DEBT")

    if not bank:
        section("Free cash flow — FCFF₀ (SEC EDGAR — primary)")
        drv("FCFF₀ base (latest FY)", s["fcff0_base"], st.EDGAR, "EDGAR FCF latest FY",
            "base-case starting FCFF", st.FMT_USD_M, "FCFF0_BASE")
        drv("FCFF₀ bear (min last 5)", s["fcff0_bear"], st.EDGAR, "EDGAR min(last 5 FY FCF)",
            "conservative trough FCFF", st.FMT_USD_M, "FCFF0_BEAR")
        drv("FCFF₀ bull (max latest, mean5)", s["fcff0_bull"], st.EDGAR,
            "EDGAR max(latest, mean last 5)", "optimistic FCFF", st.FMT_USD_M, "FCFF0_BULL")

        section("Reverse-DCF seeds (engine; an Excel CHECK re-derives — Goal Seek to re-solve)")
        drv("Assumed FCFF growth (fwd)", s["assumed_g"], st.ASSUMPTION,
            "franchise FCF CAGR, clipped ≤ min(10%, WACC−2%)",
            "forward fair-value anchor (shared across cases)", st.FMT_PCT, "ASSUMED_G")
        drv("Implied growth — base", s["implied_g_base"], st.SEED,
            "reverse_dcf.solve_implied_growth (bisection)",
            "what today's price prices in", st.FMT_PCT, "IMPLIED_G_BASE")
        drv("Implied growth — bear", s["implied_g_bear"], st.SEED,
            "reverse_dcf bisection (bear case)", "", st.FMT_PCT, "IMPLIED_G_BEAR")
        drv("Implied growth — bull", s["implied_g_bull"], st.SEED,
            "reverse_dcf bisection (bull case)", "", st.FMT_PCT, "IMPLIED_G_BULL")

    if has_norm:
        section("Normalized earnings inputs (SEC EDGAR — primary)")
        drv("Current revenue", s["revenue"], st.EDGAR, "EDGAR Revenues latest FY",
            "applied to normalized margins", st.FMT_USD_M, "REVENUE")
        drv("Mean operating margin (5y)", s["mean_opm"], st.EDGAR,
            "EDGAR 5y mean OperatingIncome/Revenue", "mid-cycle margin", st.FMT_PCT, "MEAN_OPM")
        drv("Trough operating margin", s["trough_opm"], st.EDGAR,
            "EDGAR min OperatingIncome/Revenue", "downside margin anchor", st.FMT_PCT, "TROUGH_OPM")
        drv("Interest expense", s["int_exp"], st.EDGAR, "EDGAR InterestExpense latest FY",
            "subtracted pre-tax", st.FMT_USD_M, "INT_EXP")

    if bank:
        section("Bank valuation (EDGAR / assumptions)")
        drv("Tangible book value / share", s["tbv_ps"], st.EDGAR,
            "EDGAR (equity − goodwill − intangibles) / shares", "P/TBV basis",
            st.FMT_PRICE, "TBV_PS")
        drv("Target P/TBV", s["ptbv_median"], st.ASSUMPTION,
            "default = own-history P/TBV median", "flex to your fair multiple",
            st.FMT_MULT, "PTBV_TARGET")
        drv("Target normalized P/E", s["pe_median"], st.ASSUMPTION,
            "default = own-history P/E median", "flex to your fair multiple",
            st.FMT_MULT, "NORM_PE_TARGET")

    section("Derived band statistics (own history / peers)")
    drv("Own-hist P/E p25", s["pe_p25"], st.DERIVED, "derived (own history)",
        "cheap end of own range", st.FMT_MULT, "PE_P25")
    drv("Own-hist P/E median", s["pe_median"], st.DERIVED, "derived (own history)",
        "", st.FMT_MULT, "PE_MEDIAN")
    drv("Own-hist P/E p75", s["pe_p75"], st.DERIVED, "derived (own history)",
        "dear end of own range", st.FMT_MULT, "PE_P75")
    if bank:
        drv("Own-hist P/TBV p25", s["ptbv_p25"], st.DERIVED, "derived (own history)",
            "", st.FMT_MULT, "PTBV_P25")
        drv("Own-hist P/TBV median", s["ptbv_median"], st.DERIVED, "derived (own history)",
            "", st.FMT_MULT, "PTBV_MEDIAN")
        drv("Own-hist P/TBV p75", s["ptbv_p75"], st.DERIVED, "derived (own history)",
            "", st.FMT_MULT, "PTBV_P75")
    else:
        drv("Peer P/E min", s["peer_pe_min"], st.DERIVED, "derived (peer set)",
            "cheapest peer", st.FMT_MULT, "PEER_PE_MIN")
        drv("Peer P/E median", s["peer_pe_median"], st.DERIVED, "derived (peer set)",
            "", st.FMT_MULT, "PEER_PE_MEDIAN")
        drv("Peer P/E max", s["peer_pe_max"], st.DERIVED, "derived (peer set)",
            "dearest peer", st.FMT_MULT, "PEER_PE_MAX")

    st.set_widths(ws, {1: 30, 2: 16, 3: 20, 4: 38, 5: 34})


# --------------------------------------------------------------------------- #
# Tab: DCF & Reverse-DCF (non-bank)
# --------------------------------------------------------------------------- #

def _case_row(ws, row, label, formulas, kind=st.FORMULA, fmt=None, bear=False):
    ws.cell(row=row, column=1, value=label)
    for i, f in enumerate(formulas):
        k = st.BEAR if (i == 0 and bear) else kind
        st.write_cell(ws, row, 2 + i, f, k, fmt)


def _dcf_tab(ws, mi, s, names) -> None:
    subj = mi.comps.subject
    st.title(ws, f"DCF & Reverse-DCF — {subj.ticker}")
    n = max(1, int(s["years"]))

    r_wacc, r_tg, r_fcff0, r_assumed = 5, 6, 7, 8
    st.header_row(ws, 4, ["Driver", "Bear (downside)", "Base", "Bull"])
    _case_row(ws, r_wacc, "WACC",
              ["=WACC+WACC_STRESS", "=WACC",
               "=MAX(WACC-WACC_STRESS,TERM_G+TG_STRESS+0.005)"], fmt=st.FMT_PCT, bear=True)
    _case_row(ws, r_tg, "Terminal growth",
              ["=MAX(TERM_G-TG_STRESS,0)", "=TERM_G", "=TERM_G+TG_STRESS"],
              fmt=st.FMT_PCT, bear=True)
    _case_row(ws, r_fcff0, "FCFF₀ ($)", ["=FCFF0_BEAR", "=FCFF0_BASE", "=FCFF0_BULL"],
              fmt=st.FMT_USD_M, bear=True)
    _case_row(ws, r_assumed, "Assumed FCFF growth (fwd)", ["=ASSUMED_G"] * 3,
              kind=st.ASSUMPTION, fmt=st.FMT_PCT)

    strip_start = 12
    st.header_row(ws, strip_start - 1, ["Year", "Bear", "Base", "Bull"])
    for k in range(n):
        r = strip_start + k
        ws.cell(row=r, column=1, value=k + 1)
        for i, c in enumerate(CASE_COLS):
            f = (f"=IF($A{r}<=YEARS,{c}${r_fcff0}*(1+ASSUMED_G)^$A{r}"
                 f"/(1+{c}${r_wacc})^$A{r},0)")
            st.write_cell(ws, r, 2 + i, f, st.FORMULA, st.FMT_USD_M)
    strip_end = strip_start + n - 1

    r_sumpv = strip_end + 1
    r_pvtv = r_sumpv + 1
    r_ev = r_pvtv + 1
    r_nd = r_ev + 1
    r_eq = r_nd + 1
    r_fv = r_eq + 1
    r_mos = r_fv + 1

    _case_row(ws, r_sumpv, "Σ PV of explicit FCFF",
              [f"=SUM({c}{strip_start}:{c}{strip_end})" for c in CASE_COLS], fmt=st.FMT_USD_M)
    _case_row(ws, r_pvtv, "PV of terminal value",
              [(f"=IF({c}${r_wacc}>{c}${r_tg},{c}${r_fcff0}*(1+ASSUMED_G)^YEARS"
                f"*(1+{c}${r_tg})/({c}${r_wacc}-{c}${r_tg})/(1+{c}${r_wacc})^YEARS,NA())")
               for c in CASE_COLS], fmt=st.FMT_USD_M)
    _case_row(ws, r_ev, "Enterprise value",
              [f"={c}{r_sumpv}+{c}{r_pvtv}" for c in CASE_COLS], fmt=st.FMT_USD_M)
    _case_row(ws, r_nd, "Less: net debt", ["=NET_DEBT"] * 3, fmt=st.FMT_USD_M)
    _case_row(ws, r_eq, "Equity value",
              [f"={c}{r_ev}-{c}{r_nd}" for c in CASE_COLS], fmt=st.FMT_USD_M)
    _case_row(ws, r_fv, "Fair value / share",
              [f"=IFERROR({c}{r_eq}/SHARES,NA())" for c in CASE_COLS],
              fmt=st.FMT_PRICE, bear=True)
    _case_row(ws, r_mos, "Margin of safety vs price",
              [f"=IFERROR({c}{r_fv}/PRICE-1,NA())" for c in CASE_COLS],
              fmt=st.FMT_PCT, bear=True)

    names["FV_BEAR"] = (SHEET_DCF, f"B{r_fv}")
    names["FV_BASE"] = (SHEET_DCF, f"C{r_fv}")
    names["FV_BULL"] = (SHEET_DCF, f"D{r_fv}")

    # Downside-first banner (bear first), referencing the MoS row.
    banner = (f'="Bear-case MoS  "&IFERROR(TEXT(B{r_mos},"0.0%"),"n/a")'
              f'&"      Base  "&IFERROR(TEXT(C{r_mos},"0.0%"),"n/a")'
              f'&"      Bull  "&IFERROR(TEXT(D{r_mos},"0.0%"),"n/a")')
    bc = ws.cell(row=2, column=1, value=banner)
    bc.font = Font(bold=True, color="C00000")

    # ---- Reverse DCF: implied growth + tie-out check ----
    r_rev = r_mos + 2
    ws.cell(row=r_rev, column=1,
            value="Reverse DCF — growth priced in (tie-out)").font = Font(bold=True, italic=True)
    st.header_row(ws, r_rev + 1, ["", "Bear", "Base", "Bull"])
    r_impg = r_rev + 2
    r_evimp = r_impg + 1
    r_curr = r_evimp + 1
    r_resid = r_curr + 1

    _case_row(ws, r_impg, "Implied FCFF growth (priced in)",
              ["=IMPLIED_G_BEAR", "=IMPLIED_G_BASE", "=IMPLIED_G_BULL"],
              kind=st.SEED, fmt=st.FMT_PCT)
    ig_names = ["IMPLIED_G_BEAR", "IMPLIED_G_BASE", "IMPLIED_G_BULL"]
    evimp = []
    for c, ig in zip(CASE_COLS, ig_names):
        w, tg, f0 = f"{c}{r_wacc}", f"{c}{r_tg}", f"{c}{r_fcff0}"
        x = f"((1+{ig})/(1+{w}))"
        explicit = f"{f0}*{x}*(1-{x}^YEARS)/(1-{x})"
        tv = f"{f0}*(1+{ig})^YEARS*(1+{tg})/({w}-{tg})/(1+{w})^YEARS"
        evimp.append(f"=IFERROR({explicit}+{tv},NA())")
    _case_row(ws, r_evimp, "EV @ implied growth (check)", evimp, fmt=st.FMT_USD_M)
    _case_row(ws, r_curr, "Current EV (mkt cap + net debt)", ["=MKT_CAP+NET_DEBT"] * 3,
              fmt=st.FMT_USD_M)
    _case_row(ws, r_resid, "Tie-out residual (≈ 0)",
              [f"={c}{r_evimp}-{c}{r_curr}" for c in CASE_COLS], fmt=st.FMT_USD_M)

    # Green when residual is within 0.5% of current EV (i.e. it ties out).
    green = PatternFill("solid", fgColor="C6EFCE")
    ws.conditional_formatting.add(
        f"B{r_resid}:D{r_resid}",
        FormulaRule(formula=[f"ABS(B{r_resid})<0.005*B{r_curr}"], fill=green),
    )
    ws.cell(row=r_resid + 2, column=1,
            value="Seeded implied growth ties EV→current EV on open (residual≈0). After flexing "
                  "WACC/TG/FCFF₀: Data ▸ What-If ▸ Goal Seek — Set the residual cell To 0 By "
                  "changing the matching IMPLIED_G_* input. (Engine: reverse_dcf.solve_implied_growth.)")
    st.set_widths(ws, {1: 34, 2: 16, 3: 16, 4: 16})


# --------------------------------------------------------------------------- #
# Tab: Normalized / mid-cycle earnings
# --------------------------------------------------------------------------- #

def _normalized_tab(ws, mi, s, names) -> None:
    subj = mi.comps.subject
    st.title(ws, f"Normalized / Mid-cycle Earnings — {subj.ticker}")
    st.header_row(ws, 4, ["Line (per share unless noted)", "Trough (downside)", "Mid-cycle"])
    r0 = 5
    rows = [
        ("Operating margin", "=TROUGH_OPM", "=MEAN_OPM", st.FMT_PCT, True),
        ("× Current revenue ($)", "=REVENUE", "=REVENUE", st.FMT_USD_M, False),
        ("Operating income ($)", "=TROUGH_OPM*REVENUE", "=MEAN_OPM*REVENUE", st.FMT_USD_M, False),
        ("Less: interest expense ($)", "=INT_EXP", "=INT_EXP", st.FMT_USD_M, False),
        ("Net income after tax ($)", "=(TROUGH_OPM*REVENUE-INT_EXP)*(1-TAX)",
         "=(MEAN_OPM*REVENUE-INT_EXP)*(1-TAX)", st.FMT_USD_M, False),
        ("Diluted shares", "=SHARES", "=SHARES", st.FMT_INT, False),
        ("EPS ($)", "=IFERROR((TROUGH_OPM*REVENUE-INT_EXP)*(1-TAX)/SHARES,NA())",
         "=IFERROR((MEAN_OPM*REVENUE-INT_EXP)*(1-TAX)/SHARES,NA())", st.FMT_PRICE, True),
        ("Price ($)", "=PRICE", "=PRICE", st.FMT_PRICE, False),
        ("P/E", "=IFERROR(PRICE/B{eps},NA())", "=IFERROR(PRICE/C{eps},NA())", st.FMT_MULT, True),
    ]
    r_eps = r0 + 6  # EPS row index (0-based 6th entry)
    for k, (label, fb, fc, fmt, bear) in enumerate(rows):
        r = r0 + k
        fb = fb.replace("{eps}", str(r_eps))
        fc = fc.replace("{eps}", str(r_eps))
        _case_row(ws, r, label, [fb, fc], fmt=fmt, bear=bear)
    r_pe = r0 + 8

    names["TROUGH_EPS"] = (SHEET_NORM, f"B{r_eps}")
    names["NORM_EPS"] = (SHEET_NORM, f"C{r_eps}")

    # Trailing P/E reference (seeded; not reconstructable from drivers).
    r_tr = r_pe + 2
    ws.cell(row=r_tr, column=1, value="Trailing P/E (as-reported EpsDiluted, reference)")
    st.write_cell(ws, r_tr, 2, s["trailing_pe"], st.SEED, st.FMT_MULT)

    banner = (f'="Trough (downside) P/E  "&IFERROR(TEXT(B{r_pe},"0.00")&"x","n/a")'
              f'&"      Mid-cycle P/E  "&IFERROR(TEXT(C{r_pe},"0.00")&"x","n/a")')
    bc = ws.cell(row=2, column=1, value=banner)
    bc.font = Font(bold=True, color="C00000")
    st.set_widths(ws, {1: 38, 2: 18, 3: 18})


# --------------------------------------------------------------------------- #
# Tab: Bank Valuation (replaces DCF for banks — no FCFF DCF)
# --------------------------------------------------------------------------- #

def _bank_tab(ws, mi, s, names, has_norm) -> None:
    subj = mi.comps.subject
    st.title(ws, f"Bank Valuation — {subj.ticker}  (P/TBV + normalized EPS; no FCF DCF)")
    st.header_row(ws, 4, ["Line", "Downside", "Target"])
    r = 5

    def row(label, fb, fc, fmt, bear=False):
        nonlocal r
        _case_row(ws, r, label, [fb, fc], fmt=fmt, bear=bear)
        r += 1

    ws.cell(row=r, column=1, value="P/TBV").font = Font(bold=True, italic=True)
    r += 1
    row("Tangible book value / share ($)", "=TBV_PS", "=TBV_PS", st.FMT_PRICE)
    row("P/TBV multiple", "=PTBV_P25", "=PTBV_TARGET", st.FMT_MULT, bear=True)
    row("Fair value / share ($)", "=PTBV_P25*TBV_PS", "=PTBV_TARGET*TBV_PS", st.FMT_PRICE, bear=True)
    row("Margin of safety", "=IFERROR(PTBV_P25*TBV_PS/PRICE-1,NA())",
        "=IFERROR(PTBV_TARGET*TBV_PS/PRICE-1,NA())", st.FMT_PCT, bear=True)

    if has_norm:
        r += 1
        ws.cell(row=r, column=1, value="Normalized EPS").font = Font(bold=True, italic=True)
        r += 1
        row("EPS basis ($)", "=TROUGH_EPS", "=NORM_EPS", st.FMT_PRICE, bear=True)
        row("Normalized P/E multiple", "=NORM_PE_TARGET", "=NORM_PE_TARGET", st.FMT_MULT)
        row("Fair value / share ($)", "=NORM_PE_TARGET*TROUGH_EPS",
            "=NORM_PE_TARGET*NORM_EPS", st.FMT_PRICE, bear=True)
        row("Margin of safety", "=IFERROR(NORM_PE_TARGET*TROUGH_EPS/PRICE-1,NA())",
            "=IFERROR(NORM_PE_TARGET*NORM_EPS/PRICE-1,NA())", st.FMT_PCT, bear=True)

    ws.cell(row=2, column=1,
            value="Banks: no FCFF DCF (CLAUDE.md). Downside column first; flex the target "
                  "multiples on the Inputs tab.").font = Font(bold=True, color="C00000")
    st.set_widths(ws, {1: 34, 2: 16, 3: 16})


# --------------------------------------------------------------------------- #
# Tab: Football field (relative value vs peers + own history)
# --------------------------------------------------------------------------- #

def _football_tab(ws, mi, s, names, bank, has_dcf, has_norm) -> None:
    subj = mi.comps.subject
    st.title(ws, f"Football Field — {subj.ticker}  (valuation ranges vs price)")
    st.header_row(ws, 4, ["Method", "Low (bear)", "Mid", "High (bull)", "Mid vs price"])
    r = 5
    method_rows = []

    def method(label, lo, mid, hi):
        nonlocal r
        ws.cell(row=r, column=1, value=label)
        st.write_cell(ws, r, 2, lo, st.BEAR, st.FMT_PRICE)
        st.write_cell(ws, r, 3, mid, st.FORMULA, st.FMT_PRICE)
        st.write_cell(ws, r, 4, hi, st.FORMULA, st.FMT_PRICE)
        st.write_cell(ws, r, 5, f"=IFERROR(C{r}/PRICE-1,NA())", st.FORMULA, st.FMT_PCT)
        method_rows.append(r)
        r += 1

    if has_dcf:
        method("Reverse DCF (bear/base/bull)", "=FV_BEAR", "=FV_BASE", "=FV_BULL")
    if bank and _ok(s["tbv_ps"]):
        method("Own-history P/TBV", "=PTBV_P25*TBV_PS", "=PTBV_MEDIAN*TBV_PS", "=PTBV_P75*TBV_PS")
    if has_norm and _ok(s["pe_median"]):
        method("Own-history P/E", "=TROUGH_EPS*PE_P25", "=NORM_EPS*PE_MEDIAN", "=NORM_EPS*PE_P75")
    if has_norm and not bank and _ok(s["peer_pe_median"]):
        method("Peer P/E", "=NORM_EPS*PEER_PE_MIN", "=NORM_EPS*PEER_PE_MEDIAN", "=NORM_EPS*PEER_PE_MAX")

    # Current-price reference marker.
    r += 1
    ws.cell(row=r, column=1, value="Current price (reference)").font = Font(bold=True)
    st.write_cell(ws, r, 3, "=PRICE", st.YFINANCE, st.FMT_PRICE)

    if method_rows:
        lo_r, hi_r = method_rows[0], method_rows[-1]
        ws.conditional_formatting.add(
            f"B{lo_r}:D{hi_r}",
            DataBarRule(start_type="min", end_type="max", color="8EAADB"),
        )
    ws.cell(row=2, column=1,
            value="Each row is a valuation RANGE; data bars show relative levels. Compare to the "
                  "current-price marker. Low column (bear) first. A true floating-bar chart is a "
                  "deliberate non-goal — see MODEL_NOTES to add one.").font = Font(italic=True)
    st.set_widths(ws, {1: 30, 2: 14, 3: 14, 4: 14, 5: 14})


# --------------------------------------------------------------------------- #
# Tab: Spin-off SOTP (driver skeleton; SpinCo leg seeded from the tracker)
# --------------------------------------------------------------------------- #

def _sotp_tab(ws, mi, s, names) -> None:
    rec = mi.spinoff
    st.title(ws, f"Spin-off SOTP / Stub — {mi.comps.subject.ticker}")
    ws.cell(row=2, column=1,
            value="Sum-of-the-parts skeleton. The tracker provides only SpinCo FCF + ratios "
                  "(no segment EBITDA/shares) — so parent segments are ANALYST INPUTS. Fill amber "
                  "cells from the Form 10 information statement.").font = Font(italic=True)
    st.header_row(ws, 4, ["Part / line", "Value", "Type", "Source / note"])
    r = 5

    def line(label, value, kind, source, fmt=None, formula=False):
        nonlocal r
        if formula:
            st.write_cell(ws, r, 2, value, st.FORMULA, fmt)
        else:
            st.write_cell(ws, r, 2, value, kind, fmt)
        ws.cell(row=r, column=1, value=label)
        ws.cell(row=r, column=3, value=kind)
        ws.cell(row=r, column=4, value=source)
        out = r
        r += 1
        return out

    ws.cell(row=r, column=1, value="Parent ex-SpinCo (analyst inputs)").font = Font(bold=True, italic=True)
    r += 1
    seg_ev_rows = []
    for i in (1, 2, 3):
        re = line(f"Segment {i} EBITDA ($)", 0, st.INPUT, "analyst input (Form 10 / segments)", st.FMT_USD_M)
        rm = line(f"Segment {i} EV/EBITDA (×)", 8.0, st.INPUT, "analyst input (peer multiple)", st.FMT_MULT)
        rv = line(f"Segment {i} EV ($)", f"=B{re}*B{rm}", st.FORMULA, "EBITDA × multiple",
                  st.FMT_USD_M, formula=True)
        seg_ev_rows.append(rv)
    r_sumparent = line("Σ Parent segment EV ($)",
                       "=" + "+".join(f"B{x}" for x in seg_ev_rows), st.FORMULA, "sum of parts",
                       st.FMT_USD_M, formula=True)

    r += 1
    ws.cell(row=r, column=1, value="SpinCo (seeded from tracker where available)").font = \
        Font(bold=True, italic=True)
    r += 1
    r_scfcf = line("SpinCo FCF ($)", rec.fcf if _ok(rec.fcf) else 0, st.EDGAR,
                   "EDGAR SpinCo FCF (tracker)", st.FMT_USD_M)
    r_scmult = line("SpinCo P/FCF (×)", 15.0, st.INPUT, "analyst input", st.FMT_MULT)
    r_scval = line("SpinCo equity value ($)", f"=B{r_scfcf}*B{r_scmult}", st.FORMULA,
                   "FCF × P/FCF", st.FMT_USD_M, formula=True)
    line("SpinCo net debt/EBITDA (context)", rec.net_debt_ebitda if _ok(rec.net_debt_ebitda) else None,
         st.EDGAR, "EDGAR SpinCo (tracker)", st.FMT_MULT)
    line("SpinCo ROIC (context)", rec.roic if _ok(rec.roic) else None, st.EDGAR,
         "EDGAR SpinCo (tracker)", st.FMT_PCT)
    line("Distribution ratio (context)", rec.distribution_ratio or "pending", st.EDGAR,
         "Form 10 EX-99.1 (tracker)")

    r += 1
    ws.cell(row=r, column=1, value="Consolidated → per share").font = Font(bold=True, italic=True)
    r += 1
    r_totev = line("Total EV (parent segments) ($)", f"=B{r_sumparent}", st.FORMULA,
                   "parent stub EV", st.FMT_USD_M, formula=True)
    r_nd = line("Less: consolidated net debt ($)", "=NET_DEBT", st.FORMULA, "EDGAR (Inputs)",
                st.FMT_USD_M, formula=True)
    r_eq = line("Parent equity value (ex-SpinCo) ($)", f"=B{r_totev}-B{r_nd}", st.FORMULA,
                "EV − net debt", st.FMT_USD_M, formula=True)
    r_ps = line("Implied value / share ($)", f"=IFERROR(B{r_eq}/SHARES,NA())", st.FORMULA,
                "÷ shares", st.FMT_PRICE, formula=True)
    line("vs current price (MoS)", f"=IFERROR(B{r_ps}/PRICE-1,NA())", st.FORMULA,
         "downside-first read", st.FMT_PCT, formula=True)

    flags = ", ".join(rec.downside_flags) if rec.downside_flags else "none/pending"
    ws.cell(row=r + 1, column=1, value=f"Downside flags (tracker): {flags}").font = \
        Font(bold=True, color="C00000")
    st.set_widths(ws, {1: 36, 2: 16, 3: 18, 4: 36})


# --------------------------------------------------------------------------- #
# Tab: Notes
# --------------------------------------------------------------------------- #

def _notes_tab(ws, mi, bank, has_dcf) -> None:
    st.title(ws, "Notes — read before using")
    row = 2
    # Recently-spun parents: FCF history straddles the separation, so the 5y FCF
    # CAGR (which seeds ASSUMED_G) and the bear/bull FCFF0 are distorted by the
    # SpinCo's departure. Flag it loudly — this is a real downside-first trap.
    if mi.spinoff is not None:
        spinco = mi.spinoff.spinco_name or mi.spinoff.spinco_ticker or "the SpinCo"
        warn = ws.cell(row=row, column=1, value=(
            f"⚠ RECENT SPIN-OFF ({spinco}): this parent's FCF history straddles the "
            "separation, so the 5y FCF CAGR that seeds ASSUMED_G — and the trough/bull "
            "FCFF₀ — are distorted (the latest year drops as the SpinCo leaves). Sanity-"
            "check ASSUMED_G against post-spin run-rate growth before trusting the MoS; "
            "the base case may understate fair value. Flex it on Inputs & Sources."))
        warn.font = Font(bold=True, color="C00000")
        row += 1
        ws.cell(row=row, column=1, value="")
        row += 1
    lines = [
        "",
        "These are REBUILDABLE SKELETONS seeded from a live pull. DO NOT present them in an "
        "interview as autogenerated — rebuild each formula yourself to internalize it (CLAUDE.md).",
        "Full methodology, formula derivations and the EDGAR-vs-yfinance line-item mapping live in "
        "models/MODEL_NOTES.md.",
        "",
        "Color legend (cell types):",
        "  amber  = input (editable)        green = formula (do not overtype)",
        "  blue   = EDGAR primary source    orange = yfinance (non-primary)",
        "  italic = analyst assumption      deep-orange/red = downside anchor",
        "",
        "Reverse DCF: implied growth is SEEDED from the engine's bisection solver; the tie-out "
        "residual ≈ 0 on open proves it matches `comps <TICKER>`. After flexing drivers, re-solve "
        "with Data ▸ What-If ▸ Goal Seek (set residual to 0 by changing IMPLIED_G_*).",
        "openpyxl writes formula STRINGS — it does not compute. Open in Excel and confirm no "
        "#REF!/#DIV0!/#NAME?, that the residual ties out, and that the bear column flexes.",
    ]
    if bank:
        lines.append("Bank: FCFF DCF and SOTP are omitted (not meaningful). Valuation = P/TBV + "
                     "normalized EPS; football field uses P/E + P/TBV bands.")
    for t in lines:
        ws.cell(row=row, column=1, value=t)
        row += 1
    st.set_widths(ws, {1: 110})


def _stub_tab(ws, message: str) -> None:
    st.title(ws, "Valuation")
    ws.cell(row=3, column=1, value=message)
    st.set_widths(ws, {1: 90})


# --------------------------------------------------------------------------- #
# Assembly + public entry points
# --------------------------------------------------------------------------- #

def build_workbook(mi: ModelInputs, path: Path | str) -> Path:
    """Assemble the workbook from a ModelInputs bundle and save it. Pure (no
    network) so the offline tests drive it directly with synthetic data."""
    wb = Workbook()
    names: dict[str, tuple[str, str]] = {}
    s = _seeds(mi)
    bank = mi.is_bank
    subj = mi.comps.subject
    has_dcf = (not bank) and _case(subj, "base") is not None
    has_norm = subj.normalized is not None

    ws_in = wb.active
    ws_in.title = SHEET_INPUTS
    _inputs_tab(ws_in, mi, s, names, bank, has_dcf, has_norm)

    if has_dcf:
        _dcf_tab(wb.create_sheet(SHEET_DCF), mi, s, names)
    elif bank:
        _bank_tab(wb.create_sheet(SHEET_BANK), mi, s, names, has_norm)
    else:
        _stub_tab(wb.create_sheet(SHEET_DCF),
                  "Insufficient FCF history for a reverse DCF — see Normalized & Football tabs.")

    if has_norm:
        _normalized_tab(wb.create_sheet(SHEET_NORM), mi, s, names)
    else:
        _stub_tab(wb.create_sheet(SHEET_NORM),
                  "Revenue / operating-margin history insufficient to normalize.")

    _football_tab(wb.create_sheet(SHEET_FOOTBALL), mi, s, names, bank, has_dcf, has_norm)

    if mi.spinoff is not None:
        _sotp_tab(wb.create_sheet(SHEET_SOTP), mi, s, names)

    _notes_tab(wb.create_sheet(SHEET_NOTES), mi, bank, has_dcf)

    for nm, (sheet, coord) in names.items():
        wb.defined_names.add(DefinedName(nm, attr_text=st.ref(sheet, coord)))

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path


def _pick_spin(tracker, spinco: str | None) -> SpinoffRecord | None:
    if tracker is None or not tracker.records:
        return None
    if spinco:
        key = spinco.upper()
        for rec in tracker.records:
            if (rec.spinco_ticker or "").upper() == key or (rec.spinco_cik or "") == spinco:
                return rec
    return tracker.records[0]


def build_models(
    ticker: str,
    peers: list[str] | None = None,
    *,
    wacc: float | None = None,
    terminal_growth: float | None = None,
    forecast_years: int | None = None,
    share_basis: str = "wad",
    bank: bool | None = None,
    spinco: str | None = None,
    output_path: Path | str | None = None,
    refresh: bool = False,
    comps_result: CompsResult | None = None,
) -> ModelBuildResult:
    """Pull (via the Phase-3/4 engines), seed, and write models/<TICKER>_model.xlsx.

    Reuses ``run_comps`` for all valuation numbers and ``run_track`` for the SOTP
    SpinCo leg. ``shares`` / ``net_debt`` / ``tbv_per_share`` are read from the
    same cached FinancialsFrame the DCF used, so the workbook ties to the CLI.

    Pass ``comps_result`` to reuse an already-computed CompsResult (the pipeline
    does this so comps is run once for both the tear-sheet and the model).
    """
    ticker = ticker.upper()
    comps = comps_result if comps_result is not None else run_comps(
        ticker, peers, wacc=wacc, terminal_growth=terminal_growth,
        forecast_years=forecast_years, share_basis=share_basis,
        output_path=None, fetch_prices=True, refresh=refresh,
    )  # writes comps_<TICKER>.xlsx to the gitignored cache (harmless seed artifact)

    edgar = EdgarProvider()
    ff = edgar.get_financials(ticker, use_cache=not refresh)
    shares = _last_shares(ff)
    nd = net_debt_fy(ff).dropna()
    net_debt = float(nd.iloc[-1]) if not nd.empty else 0.0

    is_bank = comps.subject.is_bank if bank is None else bank
    tbv_ps = float("nan")
    if is_bank:
        tbv = tangible_book_value_fy(ff).dropna()
        if not tbv.empty and shares == shares and shares > 0:
            tbv_ps = float(tbv.iloc[-1]) / shares

    tracker = spin = None
    if spinco is not None:
        tracker = run_track(ticker, spinco=spinco, refresh=refresh)
        spin = _pick_spin(tracker, spinco)

    mi = ModelInputs(comps=comps, shares=shares, net_debt=net_debt,
                     tbv_per_share=tbv_ps, is_bank=is_bank, spinoff=spin)
    out = Path(output_path) if output_path else (models_dir() / f"{ticker}_model.xlsx")
    build_workbook(mi, out)
    return ModelBuildResult(ticker=ticker, xlsx_path=out, is_bank=is_bank,
                            has_sotp=spin is not None, comps_result=comps, tracker_result=tracker)
